/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatastarter;

import utils.CardSwitcher;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author michael.roy-diclemen
 */
public class InfoPanel extends javax.swing.JPanel {
    public static final String CARD_NAME = "info";
    CardSwitcher switcher = null;
    /**
     * Creates new form IntroPanel
     */
    public InfoPanel(CardSwitcher p) {
        initComponents();
        switcher = p;
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        g.setFont(new Font("Dialog", Font.PLAIN, 16));
        g.drawString("This is a simulation for the progression of predators and prey.", 340, 110);
        g.drawString("To start the simulation, pick a width, height, number of predators, and number of prey and click Create grid.", 225, 135);
        g.drawString("This will create a grid with those dimensions filled the predators and prey placed in random positions.", 235, 160);
        g.drawString("When you click Start, the predators and prey will start moving one step in random directions.", 250, 185);
        g.drawString("If prey have nowhere to move, they die. If predators are next to prey, they eat the prey.", 260, 210);
        g.drawString("After each step prey make, they have a chance to reproduce in an available cell next to them.", 245, 235);
        g.drawString("This chance increases every step they survive.", 390, 260);
        g.drawString("Predators have a small chance to reproduce if they have eaten a prey in the last 10 steps.", 260, 285);
        g.drawString("If they have not eaten any prey in the last 20 steps, they die.", 340, 310);
        g.drawString("After every step, there is a small chance that forest fire erupt and kill everything in its radius.", 240, 335);
        g.drawString("Its radius and location are random.", 435, 360);
        g.drawString("The simulation ends when all prey and predators are dead.", 360, 385);
        g.drawString("You can change the speed of the simulation using the slider.", 350, 410);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 580));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(506, 506, 506)
                .addComponent(backButton)
                .addContainerGap(509, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(464, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        switcher.switchToCard(IntroPanel.CARD_NAME);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    // End of variables declaration//GEN-END:variables
}
