/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatastarter;

import utils.CardSwitcher;
import java.awt.CardLayout;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author michael.roy-diclemen
 */
public class IntroPanel extends javax.swing.JPanel {
        public static final String CARD_NAME = "intro";
    CardSwitcher switcher = null;
        PredatorSimulation simulation;
        int initialX = 420;
        int initialY = 100;
        int cellWidth;
        int cellHeight;
        Timer animTimer;

    /**
     * Creates new form IntroPanel
     */
    public IntroPanel(CardSwitcher p) {
        initComponents();
        switcher = p;
        title.setFont(new Font("Dialog", Font.BOLD, 20));
        // Create a small sample simulation to give user idea of what to expect
        simulation = new PredatorSimulation(5, 5, 1, 10);
        simulation.fillGrid();
        animTimer = new Timer(450, new IntroPanel.AnimTimerTick());
        animTimer.start();
        cellWidth = 50;
        cellHeight = 50;
        this.setFocusable(true);
        
    }
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        for (int i = 0; i < simulation.grid.length; i++){
            for (int j = 0; j < simulation.grid[i].length; j++){
                if (simulation.grid[i][j] == 2){
                    g.setColor(Color.RED);
                } else if (simulation.grid[i][j] == 1){
                    g.setColor(Color.CYAN);
                } else {
                    g.setColor(Color.WHITE);
                }
                g.fillRect(initialX + cellWidth * i, initialY + cellHeight * j, cellWidth, cellHeight);
                g.setColor(Color.BLACK);
                g.drawRect(initialX + cellWidth * i, initialY + cellHeight * j, cellWidth, cellHeight);
            }
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1080, 580));

        GameButton.setText("Game");
        GameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameButtonActionPerformed(evt);
            }
        });

        infoButton.setText("About");
        infoButton.setToolTipText("");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        title.setText("Predator and Prey Simulation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(title)
                .addContainerGap(454, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoButton)
                    .addComponent(GameButton))
                .addGap(493, 493, 493))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(GameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoButton)
                .addGap(130, 130, 130))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameButtonActionPerformed
       switcher.switchToCard(GamePanel.CARD_NAME);
    }//GEN-LAST:event_GameButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        switcher.switchToCard(InfoPanel.CARD_NAME);
    }//GEN-LAST:event_infoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GameButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private class AnimTimerTick implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            simulation.movePrey();
            simulation.movePred();
            simulation.preyRep();
            simulation.predRep();
            repaint();
        }
    }
}
